# Generated by level2solve.py
# Source: solve5.level
# Contains sticks added in the solution

sticks = [
    {"p0": [-4, 5], "p1": [2, 3], "material": "road"},
    {"p0": [2, 3], "p1": [8, -2], "material": "road"},
    {"p0": [8, -2], "p1": [14, -5], "material": "road"},
    {"p0": [14, -5], "p1": [20, -6], "material": "road"},
    {"p0": [20, -6], "p1": [25, -6], "material": "road"},
    {"p0": [25, -6], "p1": [30, -6], "material": "road"},
    {"p0": [8, -2], "p1": [10, -8], "material": "wood"},
    {"p0": [10, -8], "p1": [14, -5], "material": "wood"},
    {"p0": [15, -12], "p1": [20, -6], "material": "wood"},
    {"p0": [23, -13], "p1": [25, -6], "material": "wood"},
    {"p0": [21, -20], "p1": [23, -13], "material": "wood"},
    {"p0": [20, -23], "p1": [21, -20], "material": "wood"},
    {"p0": [20, -6], "p1": [23, -13], "material": "wood"},
    {"p0": [-38, 0], "p1": [-30, 0], "material": "road"},
    {"p0": [-35, 9], "p1": [-33, 4], "material": "wood"},
    {"p0": [-33, 4], "p1": [-30, 0], "material": "wood"},
    {"p0": [-38, 0], "p1": [-33, 4], "material": "wood"},
    {"p0": [-15, 2], "p1": [-9, 5], "material": "road"},
    {"p0": [-21, -2], "p1": [-15, 2], "material": "road"},
    {"p0": [-30, 0], "p1": [-26, -3], "material": "road"},
    {"p0": [-26, -3], "p1": [-21, -2], "material": "road"},
    {"p0": [-15, 2], "p1": [-12, -3], "material": "wood"},
    {"p0": [-21, -2], "p1": [-17, -3], "material": "wood"},
    {"p0": [-33, -10], "p1": [-29, -6], "material": "wood"},
    {"p0": [-29, -6], "p1": [-26, -3], "material": "wood"},
    {"p0": [-33, -10], "p1": [-26, -7], "material": "road"},
    {"p0": [-26, -7], "p1": [-26, -3], "material": "wood"},
]
