# Generated by level2solve.py
# Source: solve666.level
# Contains sticks added in the solution

sticks = [
    {"p0": [-38, 10], "p1": [-31, 9], "material": "road"},
    {"p0": [-31, 9], "p1": [-25, 7], "material": "road"},
    {"p0": [-25, 7], "p1": [-22, 4], "material": "road"},
    {"p0": [-31, -2], "p1": [-25, -2], "material": "road"},
    {"p0": [-25, -6], "p1": [-25, -2], "material": "wood"},
    {"p0": [-22, 4], "p1": [-18, 4], "material": "road"},
    {"p0": [-25, -2], "p1": [-20, 2], "material": "road"},
    {"p0": [-20, 2], "p1": [-20, 5], "material": "wood"},
    {"p0": [-18, 4], "p1": [-12, 6], "material": "road"},
    {"p0": [-12, 6], "p1": [-8, 0], "material": "wood"},
    {"p0": [-12, 6], "p1": [-5, 9], "material": "road"},
    {"p0": [-5, 9], "p1": [-2, 2], "material": "wood"},
    {"p0": [-5, 9], "p1": [0, 11], "material": "road"},
    {"p0": [0, 8], "p1": [0, 11], "material": "wood"},
    {"p0": [8, 0], "p1": [11, 5], "material": "wood"},
    {"p0": [11, 5], "p1": [17, 1], "material": "road"},
    {"p0": [17, 1], "p1": [22, -1], "material": "road"},
    {"p0": [22, -1], "p1": [25, -1], "material": "road"},
    {"p0": [25, -1], "p1": [31, 0], "material": "road"},
    {"p0": [31, 0], "p1": [35, 0], "material": "road"},
    {"p0": [17, 1], "p1": [18, -6], "material": "wood"},
    {"p0": [22, -1], "p1": [25, -4], "material": "wood"},
    {"p0": [0, 11], "p1": [7, 9], "material": "road"},
    {"p0": [7, 9], "p1": [11, 5], "material": "road"},
    {"p0": [-18, 8], "p1": [-12, 6], "material": "wood"},
    {"p0": [0, 8], "p1": [7, 9], "material": "wood"},
    {"p0": [28, 2], "p1": [31, 0], "material": "wood"},
]
