# Generated by level2solve.py
# Source: solve8.level
# Contains sticks added in the solution

sticks = [
    {"p0": [-34, -7], "p1": [-26, -7], "material": "road"},
    {"p0": [-4, 5], "p1": [3, 2], "material": "road"},
    {"p0": [3, 2], "p1": [9, -1], "material": "road"},
    {"p0": [9, -1], "p1": [16, -1], "material": "road"},
    {"p0": [-14, 3], "p1": [-9, 5], "material": "road"},
    {"p0": [-43, 21], "p1": [-43, 24], "material": "road"},
    {"p0": [-14, 3], "p1": [-13, 1], "material": "wood"},
    {"p0": [13, -8], "p1": [16, -4], "material": "wood"},
    {"p0": [16, -4], "p1": [16, -1], "material": "wood"},
    {"p0": [22, -1], "p1": [30, -1], "material": "road"},
    {"p0": [16, -1], "p1": [22, -1], "material": "road"},
    {"p0": [16, -4], "p1": [22, -1], "material": "wood"},
    {"p0": [18, -7], "p1": [22, -1], "material": "wood"},
    {"p0": [15, -11], "p1": [18, -7], "material": "wood"},
    {"p0": [16, -4], "p1": [18, -7], "material": "wood"},
    {"p0": [3, 2], "p1": [9, 7], "material": "wood"},
    {"p0": [-38, 0], "p1": [-35, 1], "material": "road"},
    {"p0": [-35, 1], "p1": [-30, 5], "material": "road"},
    {"p0": [-30, 5], "p1": [-28, 5], "material": "road"},
    {"p0": [-38, 3], "p1": [-35, 1], "material": "wood"},
    {"p0": [-22, 6], "p1": [-18, 4], "material": "road"},
    {"p0": [-18, 4], "p1": [-14, 3], "material": "road"},
    {"p0": [-20, -3], "p1": [-18, 4], "material": "wood"},
    {"p0": [-26, -7], "p1": [-18, -7], "material": "road"},
    {"p0": [-26, -7], "p1": [-19, -10], "material": "wood"},
]
